# Generated by Django 3.1.6 on 2021-02-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giftcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('item_no', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_send', models.BooleanField()),
                ('keyword', models.TextField()),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('price', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
