# Generated by Django 3.1.6 on 2021-02-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0002_auto_20210208_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
