# Generated by Django 3.1.6 on 2021-02-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0003_auto_20210208_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_run', models.BooleanField()),
            ],
        ),
    ]
