# Generated by Django 3.1.6 on 2021-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0004_crawlerprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlerprocess',
            old_name='pid',
            new_name='server_pid',
        ),
        migrations.AddField(
            model_name='crawlerprocess',
            name='crawler_pid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
