# Generated by Django 3.1.6 on 2021-02-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0005_auto_20210209_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerprocess',
            name='args',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
